// Cypher exporter — Neo4j CREATE statements paste-able into Neo4j Browser
// or cypher-shell.

import type { AnalysisResult } from './types.js';
import { basename } from './graph-export-shared.js';

function escapeCypher(s: string): string {
  // Neo4j single-quoted strings: escape backslashes then single quotes.
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

export function exportCypher(result: AnalysisResult): string {
  const lines: string[] = [];
  lines.push('// Generated by Grasp — paste into Neo4j Browser or cypher-shell');
  lines.push('');

  // Files
  for (const f of result.files) {
    const lang = f.path.includes('.') ? f.path.split('.').pop() ?? '' : '';
    lines.push(
      `CREATE (:File {path: '${escapeCypher(f.path)}', name: '${escapeCypher(basename(f.path))}', layer: '${escapeCypher(f.layer ?? '')}', language: '${escapeCypher(lang)}', lines: ${f.lines ?? 0}});`,
    );
  }

  // Functions + DEFINES edges
  for (const f of result.files) {
    for (const fn of f.functions ?? []) {
      lines.push(
        `CREATE (:Function {name: '${escapeCypher(fn.name)}', file: '${escapeCypher(f.path)}', line: ${fn.line ?? 0}});`,
      );
      lines.push(
        `MATCH (file:File {path: '${escapeCypher(f.path)}'}), (fn:Function {name: '${escapeCypher(fn.name)}', file: '${escapeCypher(f.path)}'}) CREATE (file)-[:DEFINES]->(fn);`,
      );
    }
  }

  // IMPORTS edges
  for (const c of result.connections) {
    lines.push(
      `MATCH (a:File {path: '${escapeCypher(c.source)}'}), (b:File {path: '${escapeCypher(c.target)}'}) CREATE (a)-[:IMPORTS]->(b);`,
    );
  }

  return lines.join('\n');
}
