// =====================================================================
// Graph exporters — emit AnalysisResult as GraphML, Cypher, and Obsidian
// Canvas (.canvas JSON). Used by the grasp_export_* MCP tools to give
// users a portable artefact that opens in yEd/Gephi/Neo4j/Obsidian.
// =====================================================================

import type { AnalysisResult } from './types.js';

// ── Helpers ────────────────────────────────────────────────────────────

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function escapeCypher(s: string): string {
  // Neo4j single-quoted strings: escape backslashes then single quotes.
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function basename(p: string): string {
  const ix = p.lastIndexOf('/');
  return ix < 0 ? p : p.slice(ix + 1);
}

// ── GraphML ────────────────────────────────────────────────────────────

export function exportGraphML(result: AnalysisResult): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<graphml xmlns="http://graphml.graphdrawing.org/xmlns">');
  lines.push('  <key id="d_label" for="node" attr.name="label" attr.type="string"/>');
  lines.push('  <key id="d_layer" for="node" attr.name="layer" attr.type="string"/>');
  lines.push('  <key id="d_lang" for="node" attr.name="language" attr.type="string"/>');
  lines.push('  <key id="d_lines" for="node" attr.name="lines" attr.type="int"/>');
  lines.push('  <key id="d_etype" for="edge" attr.name="edgeType" attr.type="string"/>');
  lines.push('  <graph id="G" edgedefault="directed">');

  for (const f of result.files) {
    const lang = f.path.includes('.') ? f.path.split('.').pop() ?? '' : '';
    lines.push(`    <node id="${escapeXml(f.path)}">`);
    lines.push(`      <data key="d_label">${escapeXml(basename(f.path))}</data>`);
    lines.push(`      <data key="d_layer">${escapeXml(f.layer ?? '')}</data>`);
    lines.push(`      <data key="d_lang">${escapeXml(lang)}</data>`);
    lines.push(`      <data key="d_lines">${f.lines ?? 0}</data>`);
    lines.push('    </node>');
  }

  let edgeCount = 0;
  for (const c of result.connections) {
    lines.push(`    <edge id="e${edgeCount++}" source="${escapeXml(c.source)}" target="${escapeXml(c.target)}">`);
    lines.push('      <data key="d_etype">imports</data>');
    lines.push('    </edge>');
  }

  lines.push('  </graph>');
  lines.push('</graphml>');
  return lines.join('\n');
}

// ── Cypher (Neo4j CREATE statements) ───────────────────────────────────

export function exportCypher(result: AnalysisResult): string {
  const lines: string[] = [];
  lines.push('// Generated by Grasp — paste into Neo4j Browser or cypher-shell');
  lines.push('');

  // Files
  for (const f of result.files) {
    const lang = f.path.includes('.') ? f.path.split('.').pop() ?? '' : '';
    lines.push(
      `CREATE (:File {path: '${escapeCypher(f.path)}', name: '${escapeCypher(basename(f.path))}', layer: '${escapeCypher(f.layer ?? '')}', language: '${escapeCypher(lang)}', lines: ${f.lines ?? 0}});`,
    );
  }

  // Functions + DEFINES edges
  for (const f of result.files) {
    for (const fn of f.functions ?? []) {
      lines.push(
        `CREATE (:Function {name: '${escapeCypher(fn.name)}', file: '${escapeCypher(f.path)}', line: ${fn.line ?? 0}});`,
      );
      lines.push(
        `MATCH (file:File {path: '${escapeCypher(f.path)}'}), (fn:Function {name: '${escapeCypher(fn.name)}', file: '${escapeCypher(f.path)}'}) CREATE (file)-[:DEFINES]->(fn);`,
      );
    }
  }

  // IMPORTS edges
  for (const c of result.connections) {
    lines.push(
      `MATCH (a:File {path: '${escapeCypher(c.source)}'}), (b:File {path: '${escapeCypher(c.target)}'}) CREATE (a)-[:IMPORTS]->(b);`,
    );
  }

  return lines.join('\n');
}

// ── Obsidian Canvas (.canvas JSON) ─────────────────────────────────────

interface CanvasNode {
  id: string;
  type: 'text';
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color: string;
}
interface CanvasEdge {
  id: string;
  fromNode: string;
  toNode: string;
}
interface CanvasDoc {
  nodes: CanvasNode[];
  edges: CanvasEdge[];
}

export function exportObsidianCanvas(result: AnalysisResult): string {
  // Group files by layer so each layer becomes a column.
  const layerGroups = new Map<string, typeof result.files>();
  for (const f of result.files) {
    const k = f.layer || 'unknown';
    if (!layerGroups.has(k)) layerGroups.set(k, []);
    layerGroups.get(k)!.push(f);
  }
  const layers = [...layerGroups.keys()].sort();

  const COL_WIDTH = 350;
  const ROW_HEIGHT = 80;
  const NODE_W = 250;
  const NODE_H = 60;

  // Stable per-file node id (use path as id is fine for Obsidian).
  const nodes: CanvasNode[] = [];
  const idByPath = new Map<string, string>();

  layers.forEach((layer, colIdx) => {
    const layerFiles = layerGroups.get(layer) ?? [];
    layerFiles.forEach((f, rowIdx) => {
      const id = `n_${nodes.length}`;
      idByPath.set(f.path, id);
      const colour = String(((colIdx % 6) + 1)); // 1..6
      nodes.push({
        id,
        type: 'text',
        text: `${f.path}\nlayer: ${layer}`,
        x: colIdx * COL_WIDTH,
        y: rowIdx * ROW_HEIGHT,
        width: NODE_W,
        height: NODE_H,
        color: colour,
      });
    });
  });

  const edges: CanvasEdge[] = [];
  let ei = 0;
  for (const c of result.connections) {
    const from = idByPath.get(c.source);
    const to = idByPath.get(c.target);
    if (!from || !to) continue;
    edges.push({ id: `e_${ei++}`, fromNode: from, toNode: to });
  }

  const doc: CanvasDoc = { nodes, edges };
  return JSON.stringify(doc, null, 2);
}
